# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Justin Hopkins
#tagline:          'A Jekyll theme'
description:      'An IT professional with a website'
url:              http://jhopkins.io
baseurl:          /

author:
  name:           'Justin Hopkins'
  url:            https://github.com/hopkinsju

paginate:         5

# Custom vars
#version:          2.0.1
resume:           http://jhopkins.io/public/justin-hopkins-systems-administrator-resume.doc
ga_tracking_id:   UA-71941066-1

github:
  repo:           https://github.com/hopkinsju/hopkinsju.github.io
  profile:        https://github.com/hopkinsju
